wandb_version: 1

max_depth:
  desc: null
  value: 18
min_samples_leaf:
  desc: null
  value: 4
min_samples_split:
  desc: null
  value: 7
n_estimators:
  desc: null
  value: 38
_wandb:
  desc: null
  value:
    python_version: 3.8.16
    cli_version: 0.15.3
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1685552796.029578
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.8.16
      5: 0.15.3
      8:
      - 5
